### ISSUE TITLE
Confusion from two ambiguous MCWrapper versions

### ISSUE THREAD

**Issue by lihaoahil** [JeffersonLab/gluex_MCwrapper#113]
I am submitting jobs using my (older, 2.7.0) version of MCWrapper on the farm, with config setting env=recon-2018_01-ver02_31.xml (where MCwrapper-v2.8.0 included).
In the log one could get confused by the two versions of MCWrapper when trying to debug:
```
=======SOFTWARE USED=======
MCwrapper version v2.7.0
MCwrapper location /group/halld/Software/builds/Linux_CentOS7.7-x86_64-gcc4.8.5/gluex_MCwrapper/gluex_MCwrapper-v2.8.0
Streaming via xrootd? 1 Event Count: 835369
BC /usr/bin/bc
python /apps/bin/python
/group/halld/Software/builds/Linux_CentOS7.7-x86_64-gcc4.8.5/halld_sim/halld_sim-4.49.0^rec180129/Linux_CentOS7.7-x86_64-gcc4.8.5/bin/mc_gen
/group/halld/Software/builds/Linux_CentOS7.7-x86_64-gcc4.8.5/hdgeant4/hdgeant4-2.39.0^rec180129/bin/Linux-g++/hdgeant4
/group/halld/Software/builds/Linux_CentOS7.7-x86_64-gcc4.8.5/halld_sim/halld_sim-4.49.0^rec180129/Linux_CentOS7.7-x86_64-gcc4.8.5/bin/mcsmear
/group/halld/Software/builds/Linux_CentOS7.7-x86_64-gcc4.8.5/halld_recon/halld_recon-recon-2018_01-ver02.9/Linux_CentOS7.7-x86_64-gcc4.8.5/bin/hd_root
```

As far as I understand, what happened is that the job-submission script `gluex_MC.py` uploads the MakeMC.csh/sh from its local repo to the farm node but the variable `$MCWRAPPER_CENTRAL `  is defined by ENV in the config. The scripts in `$MCWRAPPER_CENTRAL` actually has nothing to do with the job, but the fact its path being mentioned in the log may result in confusion.

This issue doesn't need a fix other than making the printed message more clear to avoid confusion. 
In addition, it actually provides more flexibility to allow using local MCWrapper repo for the job.

**Comment by T-Britton** [comment]
I guess I am a little confused. Yes the MakeMC from MCWRAPPER_CENTRAL is used but there is no requirement as to where that points. Thus allowing you to flexibly use a local copy or whatever you want. It is possible that I neglected to increment the version in gluex_mc.py….it is merely hard coded I don’t have any fancy system to extract a version number (this allows for the above flexibility).

I am unsure on how to make it more clear; “the hard coded string in the gluex_mc.py at the time of running is xxxxx”?

If I neglected to increment my bad, sorry for the confusion.
Thomas Britton

On Apr 16, 2024, at 4:00 PM, Hao Li ***@***.***> wrote:

﻿

I am submitting jobs using my (older, 2.7.0) version of MCWrapper on the farm, with config setting env=recon-2018_01-ver02_31.xml (where MCwrapper-v2.8.0 included).
In the log one could get confused by the two versions of MCWrapper when trying to debug:

=======SOFTWARE USED=======
MCwrapper version v2.7.0
MCwrapper location /group/halld/Software/builds/Linux_CentOS7.7-x86_64-gcc4.8.5/gluex_MCwrapper/gluex_MCwrapper-v2.8.0
Streaming via xrootd? 1 Event Count: 835369
BC /usr/bin/bc
python /apps/bin/python
/group/halld/Software/builds/Linux_CentOS7.7-x86_64-gcc4.8.5/halld_sim/halld_sim-4.49.0^rec180129/Linux_CentOS7.7-x86_64-gcc4.8.5/bin/mc_gen
/group/halld/Software/builds/Linux_CentOS7.7-x86_64-gcc4.8.5/hdgeant4/hdgeant4-2.39.0^rec180129/bin/Linux-g++/hdgeant4
/group/halld/Software/builds/Linux_CentOS7.7-x86_64-gcc4.8.5/halld_sim/halld_sim-4.49.0^rec180129/Linux_CentOS7.7-x86_64-gcc4.8.5/bin/mcsmear
/group/halld/Software/builds/Linux_CentOS7.7-x86_64-gcc4.8.5/halld_recon/halld_recon-recon-2018_01-ver02.9/Linux_CentOS7.7-x86_64-gcc4.8.5/bin/hd_root


As far as I understand, what happened is that the job-submission script gluex_MC.py uploads the MakeMC.csh/sh from its local repo to the farm node but the variable $MCWRAPPER_CENTRAL is defined by ENV in the config. The scripts in $MCWRAPPER_CENTRAL actually has nothing to do with the job, but the fact its path being mentioned in the log may result in confusion.

This issue doesn't need a fix other than making the printed message more clear to avoid confusion.
In addition, it actually provides more flexibility to allow using local MCWrapper repo for the job.

**Comment by lihaoahil** [comment]
Sorry for the confusion. 

I think I was confused by this line [https://github.com/JeffersonLab/gluex_MCwrapper/blob/a91545357a552db09e322e6f50574a74721ac2e1/MakeMC.csh#L504](url), where in log it printed out that the variable `$MCWRAPPER_VERSION` has value `v2.7.0`, which is the local version I used when running glueX_MC.py. It seems that it did extract the local tag number but it appears that this variable should get the version number from the arg $1 (as in line 106) which is the configured ENV file.

**Comment by s6pepaul** [comment]
I guess this is resolved and can be closed.
