### ISSUE TITLE
generator post-processing

### ISSUE THREAD

**Issue by sdobbs** [JeffersonLab/gluex_MCwrapper#13]
It would be good to run option post-processors on the output of a generator.  These would include:

- decay_evtgen, which can apply various decay models to the generated particles.  An input file "userDecay.dec" is often passed.
- Various python scripts for filtering/applying fiducial cuts, things like that.  We can put these in some standard halld_sim location, though would be nice to specify them on the command line too

**Comment by T-Britton** [comment]
concerning bullet point two:  "run script x which takes in an hddm file and outputs an hddm file before geant"?

**Comment by T-Britton** [comment]
done....finally. Will be in the next release
