### ISSUE TITLE
access to job configuration/environment

### ISSUE THREAD

**Issue by sdobbs** [JeffersonLab/gluex_MCwrapper#15]
For the web site, it would be nice if there was a way to easily access (a button maybe?) the input environment and configuration files for a job.  If I look at the output directory, I can usually figure out what I need, but for the purposes of debugging it would help if this information was more easily accessible.

**Comment by T-Britton** [comment]
you mean like the MC.config file and command (with arguments) MCWrapper was run with?

**Comment by sdobbs** [comment]
that would totally help

**Comment by T-Britton** [comment]
right click on a project on the dashboard.  Select "Get MC.config File".  You should get a prompt with the file's text in a prompt.  Use your favorite method to copy it and paste it anywhere you'd like
