### ISSUE TITLE
Better parsing in error messages

### ISSUE THREAD

**Issue by sdobbs** [JeffersonLab/gluex_MCwrapper#17]
In the emails that are sent when the test job fails, the error log is not properly parsed into plain text and it's really annoying to filter the newlines in by hand.  An example is reproduced below:

Errors:

b'Warning from GlueXDetectorConstruction::ConstructSDandField - unsupported sensitive volume TAC1 found in geometry definition.\nG4WT0 > Warning from GlueXDetectorConstruction::ConstructSDandField - unsupported sensitive volume TAC1 found in geometry definition.\nJANA ERROR>>Problem loading CCAL/mc_energy from CCDB!\nJANA ERROR>>Problem loading CCAL/mc_time from CCDB!\nsrc/JANA/JGeometryXML.cc:348 Node or attribute not found for xpath "//section/composition/posXYZ[@volume=\'DIRC\']/@X_Y_Z".\nlibraries/HDGEOMETRY/DGeometry.cc:1741 Unable to retrieve DIRC position.\nJANA ERROR>> didn\'t sleep full 0.5 seconds!\n\n\n\n===========================================================\nThere was a crash.\nThis is the entire stack trace of all threads:\n===========================================================\n\nThread 4 (Thread 0x7f14d52eb700 (LWP 1643606)):\n#0  0x00007f14de0b9aab in do_futex_wait.constprop.1 () from /lib64/libpthread.so.0\n#1  0x00007f14de0b9b3f in __new_sem_wait_slow.cons
 tprop.0 () from /lib64/libpthread.so.0\n#2  0x00007f14de0b9bdb in sem_wait\n\nGLIBC_2.2.5 () from /lib64/libpthread.so.0\n#3  0x00007f14dd0a93d6 in XrdPosixFile::DelayedDestroy(void*) () from /lib64/libXrdPosix.so.2\n#4  0x00007f14d8618537 in XrdSysThread_Xeq () from /lib64/libXrdUtils.so.2\n#5  0x00007f14de0b3dd5 in start_thread () from /lib64/libpthread.so.0\n#6  0x00007f14dd3bab3d in clone () from /lib64/libc.so.6\n\nThread 3 (Thread 0x7f14c17a3700 (LWP 1643627)):\n#0  0x00007f14de0b7945 in pthread_cond_wait\n\nGLIBC_2.3.2 () from /lib64/libpthread.so.0\n#1  0x0000000001071ba0 in jana::JApplication::EventBufferThread (this=this\nentry=0x7fff4a8931c0) at src/JANA/JApplication.cc:742\n#2  0x0000000001071e69 in LaunchEventBufferThread (arg=0x7fff4a8931c0) at src/JANA/JApplication.cc:666\n#3  0x00007f14de0b3dd5 in start_thread () from /lib64/libpthread.so.0\n#4  0x00007f14dd3bab3d in clone () from /lib64/libc.so.6\n\nThread 2 (Thread 0x7f14bbfff700 (LWP 1643628)):\n#0  0x00007f14dd38
 1159 in waitpid () from /lib64/libc.so.6\n#1  0x00007f14dd2fede2 in do_system () from /lib64/libc.so.6\n#2  0x00007f14dd2ff191 in system () from /lib64/libc.so.6\n#3  0x00007f14e3c67b19 in TUnixSystem::StackTrace (this=0x23bdda0) at /u/group/halld/Software/builds/Linux_RHEL7-x86_64-gcc4.8.5/root/root-6.08.06/core/unix/src/TUnixSystem.cxx:2405\n#4  0x00007f14e3c6a3ec in TUnixSystem::DispatchSignals (this=0x23bdda0, sig=kSigSegmentationViolation) at /u/group/halld/Software/builds/Linux_RHEL7-x86_64-gcc4.8.5/root/root-6.08.06/core/unix/src/TUnixSystem.cxx:3625\n#5  <signal handler called>\n#6  Calc_RFBunchShift (this=<optimized out>, locTimeToStepTo=<error reading variable: Cannot access memory at address 0x60>, locTimeToStep=139485856.50098124) at libraries/ANALYSIS/DSourceComboTimeHandler.h:302\n#7  Calc_RFBunchShift (locTimeToStepTo=<error reading variable: Cannot access memory at address 0x60>, this=0x7f148ab3c9e0) at libraries/ANALYSIS/DSourceComboTimeHandler.h:68\n#8  DAnalysis::
 DSourceComboVertexer::Calc_VertexTimeOffsets_WithBeam (this=0x7f148ab38550, locReactionVertexInfo=0x7f149457ed40, locReactionFullComboUse=std::tuple containing = {...}, locReactionFullCombo=locReactionFullCombo\nentry=0x7f148ab4dc20, locBeamParticle=0x7f14ad65a4e0) at libraries/ANALYSIS/DSourceComboVertexer.cc:257\n#9  0x000000000085a4db in DAnalysis::DSourceComboer::Combo_WithBeam (this=this\nentry=0x7f1495b7f200, locReactions=std::vector of length 1, capacity 1 = {...}, locReactionVertexInfo=locReactionVertexInfo\nentry=0x7f149457ed40, locReactionFullComboUse=std::tuple containing = {...}, locReactionFullCombo=0x7f148ab4dc20, locRFBunch=0, locOutputComboMap=std::unordered_map with 1 elements = {...}) at libraries/ANALYSIS/DSourceComboer.cc:1708\n#10 0x00000000008690b6 in DAnalysis::DSourceComboer::Combo_WithNeutralsAndBeam (this=this\nentry=0x7f1495b7f200, locReactions=std::vector of length 1, capacity 1 = {...}, locReactionVertexInfo=locReactionVertexInfo\nentry=0x7f149457ed40, l
 ocPrimaryComboUse=std::tuple containing = {...}, locReactionChargedCombo=0x7f148ab4dcc0, locBeamBunches_Charged=std::vector of length 1, capacity 1 = {...}, locOutputComboMap=std::unordered_map with 1 elements = {...}) at libraries/ANALYSIS/DSourceComboer.cc:1659\n#11 0x000000000086a0b1 in DAnalysis::DSourceComboer::Build_ParticleCombos (this=0x7f1495b7f200, locReactionVertexInfo=0x7f149457ed40) at libraries/ANALYSIS/DSourceComboer.cc:1526\n#12 0x000000000069d50e in DAnalysisResults_factory::evnt (this=0x7f14b412e580, locEventLoop=0x7f14b40008c0, eventnumber=<optimized out>) at libraries/ANALYSIS/DAnalysisResults_factory.cc:282\n#13 0x0000000000690a13 in jana::JFactory<DAnalysisResults>::Get (this=this\nentry=0x7f14b412e580, d=std::vector of length 0, capacity 0) at /u/group/halld/Software/builds/Linux_RHEL7-x86_64-gcc4.8.5/jana/jana_0.7.9p1^ccdb166/Linux_RHEL7-x86_64-gcc4.8.5/include/JANA/JFactory.h:295\n#14 0x0000000000691574 in jana::JEventLoop::GetFromFactory<DAnalysisResults> (
 this=this\nentry=0x7f14b40008c0, t=std::vector of length 0, capacity 0, tag=tag\nentry=0x10e7827 "", data_source=\n0x7f14bbff8190: 3824308784, allow_deftag=allow_deftag\nentry=true) at /u/group/halld/Software/builds/Linux_RHEL7-x86_64-gcc4.8.5/jana/jana_0.7.9p1^ccdb166/Linux_RHEL7-x86_64-gcc4.8.5/include/JANA/JEventLoop.h:452\n#15 0x0000000000691844 in jana::JEventLoop::Get<DAnalysisResults> (this=this\nentry=0x7f14b40008c0, t=std::vector of length 0, capacity 0, tag=tag\nentry=0x10e7827 "", allow_deftag=allow_deftag\nentry=true) at /u/group/halld/Software/builds/Linux_RHEL7-x86_64-gcc4.8.5/jana/jana_0.7.9p1^ccdb166/Linux_RHEL7-x86_64-gcc4.8.5/include/JANA/JEventLoop.h:309\n#16 0x0000000000709bc0 in DEventWriterROOT::Fill_DataTrees (this=this\nentry=0x7f1494496b90, locEventLoop=locEventLoop\nentry=0x7f14b40008c0, locDReactionTag="ReactionFilter") at libraries/ANALYSIS/DEventWriterROOT.cc:960\n#17 0x00007f14c17ea752 in DEventProcessor_ReactionFilter::evnt (this=<optimized out>, locEv
 entLoop=0x7f14b40008c0, locEventNumber=<optimized out>) at plugins/Analysis/ReactionFilter/DEventProcessor_ReactionFilter.cc:74\n#18 0x000000000108c41a in jana::JEventLoop::OneEvent (this=this\nentry=0x7f14b40008c0) at src/JANA/JEventLoop.cc:693\n#19 0x000000000108d3b4 in jana::JEventLoop::Loop (this=this\nentry=0x7f14b40008c0) at src/JANA/JEventLoop.cc:496\n#20 0x000000000106466a in LaunchThread (arg=0x7fff4a8931c0) at src/JANA/JApplication.cc:1382\n#21 0x00007f14de0b3dd5 in start_thread () from /lib64/libpthread.so.0\n#22 0x00007f14dd3bab3d in clone () from /lib64/libc.so.6\n\nThread 1 (Thread 0x7f14e4c64200 (LWP 1643605)):\n#0  0x00007f14de0baeed in nanosleep () from /lib64/libpthread.so.0\n#1  0x000000000106da0d in jana::JApplication::Run (this=this\nentry=0x7fff4a8931c0, proc=proc\nentry=0x285db70, Nthreads=<optimized out>, Nthreads\nentry=0) at src/JANA/JApplication.cc:1613\n#2  0x000000000063f29c in main (narg=5, argv=0x7fff4a893828) at programs/Analysis/hd_root/hd_root.cc:45
 \n===========================================================\n\n\nThe lines below might hint at the cause of the crash.\nYou may get help by asking at the ROOT forum http://root.cern.ch/forum.\nOnly if you are really convinced it is a bug in ROOT then please submit a\nreport at http://root.cern.ch/bugs. Please post the ENTIRE stack trace\nfrom above as an attachment in addition to anything else\nthat might help us fixing this issue.\n===========================================================\n#6  Calc_RFBunchShift (this=<optimized out>, locTimeToStepTo=<error reading variable: Cannot access memory at address 0x60>, locTimeToStep=139485856.50098124) at libraries/ANALYSIS/DSourceComboTimeHandler.h:302\n#7  Calc_RFBunchShift (locTimeToStepTo=<error reading variable: Cannot access memory at address 0x60>, this=0x7f148ab3c9e0) at libraries/ANALYSIS/DSourceComboTimeHandler.h:68\n#8  DAnalysis::DSourceComboVertexer::Calc_VertexTimeOffsets_WithBeam (this=0x7f148ab38550, locReactionVertexI
 nfo=0x7f149457ed40, locReactionFullComboUse=std::tuple containing = {...}, locReactionFullCombo=locReactionFullCombo\nentry=0x7f148ab4dc20, locBeamParticle=0x7f14ad65a4e0) at libraries/ANALYSIS/DSourceComboVertexer.cc:257\n#9  0x000000000085a4db in DAnalysis::DSourceComboer::Combo_WithBeam (this=this\nentry=0x7f1495b7f200, locReactions=std::vector of length 1, capacity 1 = {...}, locReactionVertexInfo=locReactionVertexInfo\nentry=0x7f149457ed40, locReactionFullComboUse=std::tuple containing = {...}, locReactionFullCombo=0x7f148ab4dc20, locRFBunch=0, locOutputComboMap=std::unordered_map with 1 elements = {...}) at libraries/ANALYSIS/DSourceComboer.cc:1708\n#10 0x00000000008690b6 in DAnalysis::DSourceComboer::Combo_WithNeutralsAndBeam (this=this\nentry=0x7f1495b7f200, locReactions=std::vector of length 1, capacity 1 = {...}, locReactionVertexInfo=locReactionVertexInfo\nentry=0x7f149457ed40, locPrimaryComboUse=std::tuple containing = {...}, locReactionChargedCombo=0x7f148ab4dcc0, locBe
 amBunches_Charged=std::vector of length 1, capacity 1 = {...}, locOutputComboMap=std::unordered_map with 1 elements = {...}) at libraries/ANALYSIS/DSourceComboer.cc:1659\n#11 0x000000000086a0b1 in DAnalysis::DSourceComboer::Build_ParticleCombos (this=0x7f1495b7f200, locReactionVertexInfo=0x7f149457ed40) at libraries/ANALYSIS/DSourceComboer.cc:1526\n#12 0x000000000069d50e in DAnalysisResults_factory::evnt (this=0x7f14b412e580, locEventLoop=0x7f14b40008c0, eventnumber=<optimized out>) at libraries/ANALYSIS/DAnalysisResults_factory.cc:282\n#13 0x0000000000690a13 in jana::JFactory<DAnalysisResults>::Get (this=this\nentry=0x7f14b412e580, d=std::vector of length 0, capacity 0) at /u/group/halld/Software/builds/Linux_RHEL7-x86_64-gcc4.8.5/jana/jana_0.7.9p1^ccdb166/Linux_RHEL7-x86_64-gcc4.8.5/include/JANA/JFactory.h:295\n#14 0x0000000000691574 in jana::JEventLoop::GetFromFactory<DAnalysisResults> (this=this\nentry=0x7f14b40008c0, t=std::vector of length 0, capacity 0, tag=tag\nentry=0x10e78
 27 "", data_source=\n0x7f14bbff8190: 3824308784, allow_deftag=allow_deftag\nentry=true) at /u/group/halld/Software/builds/Linux_RHEL7-x86_64-gcc4.8.5/jana/jana_0.7.9p1^ccdb166/Linux_RHEL7-x86_64-gcc4.8.5/include/JANA/JEventLoop.h:452\n#15 0x0000000000691844 in jana::JEventLoop::Get<DAnalysisResults> (this=this\nentry=0x7f14b40008c0, t=std::vector of length 0, capacity 0, tag=tag\nentry=0x10e7827 "", allow_deftag=allow_deftag\nentry=true) at /u/group/halld/Software/builds/Linux_RHEL7-x86_64-gcc4.8.5/jana/jana_0.7.9p1^ccdb166/Linux_RHEL7-x86_64-gcc4.8.5/include/JANA/JEventLoop.h:309\n#16 0x0000000000709bc0 in DEventWriterROOT::Fill_DataTrees (this=this\nentry=0x7f1494496b90, locEventLoop=locEventLoop\nentry=0x7f14b40008c0, locDReactionTag="ReactionFilter") at libraries/ANALYSIS/DEventWriterROOT.cc:960\n#17 0x00007f14c17ea752 in DEventProcessor_ReactionFilter::evnt (this=<optimized out>, locEventLoop=0x7f14b40008c0, locEventNumber=<optimized out>) at plugins/Analysis/ReactionFilter/DEv
 entProcessor_ReactionFilter.cc:74\n#18 0x000000000108c41a in jana::JEventLoop::OneEvent (this=this\nentry=0x7f14b40008c0) at src/JANA/JEventLoop.cc:693\n#19 0x000000000108d3b4 in jana::JEventLoop::Loop (this=this\nentry=0x7f14b40008c0) at src/JANA/JEventLoop.cc:496\n#20 0x000000000106466a in LaunchThread (arg=0x7fff4a8931c0) at src/JANA/JApplication.cc:1382\n#21 0x00007f14de0b3dd5 in start_thread () from /lib64/libpthread.so.0\n#22 0x00007f14dd3bab3d in clone () from /lib64/libc.so.6\n\n===========================================================\n\n\nJANA ERROR>> didn\'t sleep full 0.5 seconds!\n'

**Comment by T-Britton** [comment]
The \n in there come from there being \\n in the std error from Popen's communicate.
I have added the corresponding line:errors=str(errors).replace('\\n', '\n') and it seems to have fixed things
