### ISSUE TITLE
Request for more software info in confirmation e-mail

### ISSUE THREAD

**Issue by jrstevenjlab** [JeffersonLab/gluex_MCwrapper#22]
Could you include some information on software versions in the confirmation e-mail sent out when a request is made on the webpage?  This could make it easier for users to keep track of what software versions their using without going to the Dashboard.

My thought was a format for the e-mail like what's displayed on the submit form:

halld_recon version: xxx
halld_sim version: yyy
hdgeant4 version: zzz or N/A if geant 3 was used
version set: blah.xml
ReactionFilter version: rrr (if used)

**Comment by T-Britton** [comment]
The only one I can't do trivially is the geant version (because the user never explicitly picks it.  The others should be in
