### ISSUE TITLE
Crash with bash

### ISSUE THREAD

**Issue by markdalton** [JeffersonLab/gluex_MCwrapper#23]
There's a crash with bash which makes it unusable as far as I can tell.  Thomas is aware and the DEV version is patched.  This is just a reminder than it needs to be put in the production version.

**Comment by T-Britton** [comment]
As a note.  The DEV version being released is waiting on final fixes to allow MCwrapper to run on the farm in the container.  Hopefully, this will start working in a couple of days and the release can happen end of week

**Comment by T-Britton** [comment]
new release solves this issue
