### ISSUE TITLE
Remove cuts card from Gcontrol files

### ISSUE THREAD

**Issue by s6pepaul** [JeffersonLab/gluex_MCwrapper#26]
See discussion and Richards comment in 
https://github.com/JeffersonLab/HDGeant4/issues/149#issuecomment-622411857

**Comment by T-Britton** [comment]
Thank you. It will be dealt with momentarily. As a work around one may run with a custom Gcontrol with the offending line commented out. I don’t think the effect should be huge but may be more or less severe depending on the sample produced

**Comment by s6pepaul** [comment]
I am currently testing how large the effect is. Either way it should be changed and propagated to the webpage asap.

Am 02.05.2020 um 11:34 schrieb T-Britton <notifications@github.com<mailto:notifications@github.com>>:



Thank you. It will be dealt with momentarily. As a work around one may run with a custom Gcontrol with the offending line commented out. I don’t think the effect should be huge but may be more or less severe depending on the sample produced

**Comment by T-Britton** [comment]
It has been dealt with.  And on the DEV version, which the bot uses (just for this reason). for those running more locally you can point MCWERAPPER_CENTRAL to /group/halld/gluex_MCwrapper until I get an official release out.
