### ISSUE TITLE
Log file names

### ISSUE THREAD

**Issue by markdalton** [JeffersonLab/gluex_MCwrapper#27]
The names of the log files do not seem to be using the TAG card from the input file (contrary to the names of other output files) only the run number is used.  This makes them susceptible to clobbering and finding the appropriate file difficult.  Please introduce consistent naming.

**Comment by T-Britton** [comment]
Because the log names are set outside of running the STUBNAMES were neglecting the tag string.  I have now made log files include the tag.  Names now should be WORKFLOW_[TAG]_RUNNUM_FILENUM if TAG is set

This change only affects the DEV branch and will be included in the next release
