### ISSUE TITLE
Improvements for running over input HDDM files

### ISSUE THREAD

**Issue by sdobbs** [JeffersonLab/gluex_MCwrapper#28]
There are a couple things I came across that would make it more convenient when passing a file of thrown events to MCWrapper instead of using one of the generators:

- a blank argument to GENERATOR_CONFIG is not properly handled
- why bother loading beam parameters from RCDB (or otherwise) if they are never used?  this is a hassle

**Comment by T-Britton** [comment]
What do you mean not properly handled? There are a couple of generators that I think don't use the configs....though maybe I fixed that a while ago. Or do you mean if you don't have a config it crashes?  If the latter I'll improve the handling for passed in files 

Laziness.  I can skip that step in the case where you pass in a file AND you don't have TAGONLY or beamphotons backgrounds

**Comment by sdobbs** [comment]
If you pass an empty string for the generator config in the config file
then this gets propagated through, so the shell script has one fewer
arguments than it is expecting.

**Comment by T-Britton** [comment]
Ah! Good catch.  Wonder when I introduced this one.....I'll fix it soon

**Comment by T-Britton** [comment]
should be all done on the DEV branch
