### ISSUE TITLE
grep: (standard input): Input/output error after running MCWrapper

### ISSUE THREAD

**Issue by jonzarling** [JeffersonLab/gluex_MCwrapper#32]
Running on the jlab farm, I seem to always get 
`grep: (standard input): Input/output error
grep: (standard input): Input/output error
grep: (standard input): Input/output error
`
after running. I have to hit enter a few times before I can type things into my terminal again, and I lose anything I type beforehand. Probably medium-low priority, but wanted to mention.

**Comment by T-Britton** [comment]
what are you running? csh or bash? Interactive? have a config file? What version Set? What version of MCwrapper?

I can't try to reproduce this as an MCwrapper issue without knowing all of the conditions leading to it.

**Comment by jonzarling** [comment]
Forgot to mention, interactively in csh. Try running the command 
`/group/halld/Software/builds/Linux_CentOS7.7-x86_64-gcc4.8.5/gluex_MCwrapper/gluex_MCwrapper-v2.5.0/gluex_MC.py /w/halld-scifs17exp/home/jzarling/ForPeople/ForThomas/MC.config 30300 10 batch=0`

**Comment by T-Britton** [comment]
can you send me the std out from a run (as I give below)?  I cannot at present reproduce this issue on the DEV branch (I like checking here first to know if it is an issue persisting).  I'll try with your version shortly.
*********************************
Welcome to v2.5.1 of MCwrapper
Thomas Britton 06/26/20
*********************************
Locally simulating 10 particle_gun Events
Wed Jul 22 13:34:36 EDT 2020
what path?
no_sqlite


Detected c-shell
Radiator thickness set...
Polarization angle set...
11.608
Electron beam energy set...
Coherent peak set...
eBEAM energy set...
Colimator size set...
beam (on) current set...
BGrate set...
This job has been configured to run at:  JLAB : ifarm1801.jlab.org
Job started:  Wed Jul 22 13:34:38 EDT 2020
Simulating the Experiment:  gluex
ccdb sqlite path:  no_sqlite mysql://ccdb_user@hallddb.jlab.org/ccdb
rcdb sqlite path:  no_sqlite mysql://rcdb@hallddb.jlab.org/rcdb
Producing file number: 0
Containing:  10/10000 events
Running location: ./
Output location: /w/halld-scifs17exp/halld2/home/tbritton/john/TEST/
Environment file:  /u/home/jzarling/gx_env/JEF_standard_env.csh
Analysis Environment file:  no_Analysis_env
Context: variation=mc calibtime=timegoeshere
Geometry URL: ccdb:///GEOMETRY/main_HDDS.xml
Reconstruction calibtime: notime
Run Number: 30300
Electron beam current to use: 100 uA
Electron beam energy to use: 11.608 GeV
Radiator Thickness to use: 58e-6 m
Collimator Diameter: 0.0050 m
Photon Energy between 3 and 11.6 GeV
Polarization Angle: 45.0 degrees
Coherent Peak position: 8.82000000000000000000
----------------------------------------------
Run generation step? 1  Will be cleaned? 1
Flux Hist to use:  ccdb  :  unset
Polarization to use:  0.4  :  unset
Using particle_gun  with config: /w/halld-scifs17exp/halld2/home/tbritton/john/particle_gun.cfg
Will run No postprocessing after generator with configuration: Default
----------------------------------------------
Run geant step? 1  Will be cleaned? 1
Using geant4
Custom Gcontrol? 0
Background to use: None
Random trigger background to use: none
BGRATE will be set to: rcdb GHz (if applicable)
Run mcsmear? 1  Will be cleaned? 1
----------------------------------------------
Run reconstruction? 1  Will be cleaned? 0
With additional plugins: None
==============================================


=======SOFTWARE USED=======
MCwrapper version v2.5.1
MCwrapper location /group/halld/gluex_MCwrapper/
Streaming via xrootd? 0 Event Count: -1
BC /usr/bin/bc
python /apps/bin/python
particle_gun: Command not found.
/group/halld/Software/builds/Linux_CentOS7.7-x86_64-gcc4.8.5/hdgeant4/hdgeant4-2.9.0/bin/Linux-g++/hdgeant4
/w/halld-scifs17exp/halld2/home/tbritton/GlueX_Software/halld_sim_master//Linux_CentOS7.7-x86_64-gcc4.8.5/bin/mcsmear
/w/halld-scifs17exp/halld2/home/tbritton/GlueX_Software/halld_recon_master//Linux_CentOS7.7-x86_64-gcc4.8.5/bin/hd_root

**Comment by T-Britton** [comment]
The errors occur after the last line of gluex_MC.py code and used to not happen in the past and this code has not been modified in like 2+ years.  An incident has been submitted (on your behalf) as I believe the problem lies on the system side.

**Comment by T-Britton** [comment]
no one can figure out where this is coming from.  Closing the issue for now. Sorry for the annoyance
