### ISSUE TITLE
A couple FAQs to add to the submission page

### ISSUE THREAD

**Issue by sdobbs** [JeffersonLab/gluex_MCwrapper#35]
It would be nice to link somehow on the submission page to the following two wiki pages, since they contain answers to some FAQs by users:

how to choose software versions:  https://halldweb.jlab.org/wiki/index.php/How_to_choose_software_versions_on_the_MC_submission_form
how to find run ranges/RCDB queries: 
https://halldweb.jlab.org/wiki-private/index.php/GlueX_Phase-I_Dataset_Summary

**Comment by T-Britton** [comment]
added clickable question marks next to the relevant fields
