### ISSUE TITLE
Need ability to set additional HTCondor options for local clusters

### ISSUE THREAD

**Issue by sdobbs** [JeffersonLab/gluex_MCwrapper#36]
Hi, my local cluster requires the following line in the submission script to that priorities, etc. are properly handled:

+AccountingGroup = "group_local"

It would be good to have an option in the MCWrapper config file to set this configuration.

**Comment by T-Britton** [comment]
can you try the following after pulling the DEV branch:

just include CONDOR_MAGIC=AccountingGroup:"group_local"
and run

see what happens and let me know ;)

CONDOR_MAGIC can be used multiple times and should automagically prepend the '+' and change the first ':' to '=' for every "magic" entry

**Comment by sdobbs** [comment]
OK, I'm testing this out.  BTW, it would be better if one could do something like this:

CONDOR_MAGIC="AccountingGroup=\"group_local\""

**Comment by sdobbs** [comment]
uh oh, markdown is too smart!

<pre>CONDOR_MAGIC="AccountingGroup=\"group_local\""</pre>

**Comment by T-Britton** [comment]
This is working for now though right?

**Comment by sdobbs** [comment]
well, this solution works, but ended up looking into this more, and apparently recent versions of condor have deprecated this JobAd modification for the more reasonable
`accounting_group = group_local`
So, it would be good if the CONDOR_MAGIC didn't automagically prepend the plus sign and left that up to the user

**Comment by T-Britton** [comment]
Trivially done...tomorrow 😀

Thomas Britton

On Sep 23, 2020, at 5:18 PM, Sean Dobbs <notifications@github.com> wrote:

﻿

well, this solution works, but ended up looking into this more, and apparently recent versions of condor have deprecated this JobAd modification for the more reasonable
accounting_group = group_local
So, it would be good if the CONDOR_MAGIC didn't automagically prepend the plus sign and left that up to the user

**Comment by T-Britton** [comment]
okay no more prepended and no awkward ':'->'='.  This means that you can stack CONDOR_MAGIC to add custom lines

such as: `CONDOR_MAGIC=+accounting_group=group_local` will add the line `+accounting_group=group_local` to the submit file
