### ISSUE TITLE
add option for custom jana config files

### ISSUE THREAD

**Issue by aaust** [JeffersonLab/gluex_MCwrapper#40]
on the MCWrapper submit form, it could be useful to supply a jana config file for the analysis step instead of a reaction filter line, so that one can run the analysis library with non-default cuts or add other plugins.

**Comment by T-Britton** [comment]
this is in and working.  A couple notes:
you MUST include danarest in addition to the other plugins right now for MCwrapper-bot as an exception has not been written in the data return check (it expects a danarest)
if you supply NTHREADS please set it equal to 1
