### ISSUE TITLE
Submit GUI's right hand panel is blank

### ISSUE THREAD

**Issue by nsjarvis** [JeffersonLab/gluex_MCwrapper#43]
The right hand panel on SubmitSim is blank.  Every now and then, as I complete the form, it bounces up and down, but it remains blank.  I am worried that I might be missing out on reading something useful.
<img width="1364" alt="mcwexample" src="https://user-images.githubusercontent.com/15655254/99578571-03831200-29ab-11eb-8c8f-f6e7d86ce61d.png">

**Comment by T-Britton** [comment]
it is failing to read from the .xml most likely.  The only info ever shown there is that so no functionality is actually lost. I'll leave this issue up for a little bit but don't have any ready knobs to turn....

**Comment by T-Britton** [comment]
working now.  Possibly some residuals from maintenance day....
