### ISSUE TITLE
SubmitSim: The greyed out text in the RCDB conditions box is overflowing the box and cannot be read 

### ISSUE THREAD

**Issue by nsjarvis** [JeffersonLab/gluex_MCwrapper#45]
The grey suggested text in some of the form fields is much too large and cannot be read or scrolled through.  I suggest that you remove it.  This would take attention away from the suggested text and direct the newbie user to the help button instead, which is much more useful (for the RCDB conditions in particular).

<img width="1364" alt="mcwexample" src="https://user-images.githubusercontent.com/15655254/99578371-bb63ef80-29aa-11eb-8c1e-9ff91fc7f82d.png">

**Comment by T-Britton** [comment]
the width is screen size dependent (among a few other things).  Thus the solution is to use a bigger screen.  I cannot "fix this" and am closing the issue.  You can also get this information from the help button, whose issue (#44) will be addressed in minutes

**Comment by nsjarvis** [comment]
You **can** fix it, by removing the text.  :-)   When confronted with a totally blank text box, the user is more likely to spot the friendly blue question mark next to it.

**Comment by T-Britton** [comment]
split the difference.  I want people to know it is optional and indicate the default value.  Modified the text

**Comment by nsjarvis** [comment]
Oh!!  I did not realise that it was optional!   Yes, this is much better, it was a good idea to write "Optional" first. The part that is cut off at the end is not important.
