### ISSUE TITLE
MCW add reactions suggestions

### ISSUE THREAD

**Issue by nsjarvis** [JeffersonLab/gluex_MCwrapper#48]
I did find the include/save reaction buttons a bit confusing at first.

I suggest that you change 'include reaction' to 'add this to proposed list of reactions'
change 'save reactions' to 'save list of reactions and exit'
and maybe add another button 'clear proposed list of reactions' to start all over again.

Would it be possible to add sanity checks to the reactions specified?  eg make sure that baryon number is conserved?
This could avoid potentially wasted compute time due to user error. 

There's a typo partical in line 2.  That was just distracting. :-)

**Comment by T-Britton** [comment]
I have changed the names to be more descriptive.

I am going to veto the clear all (just close the window without saving and come back ;) )

in principle yes. This would be a great graduate student project.  It will require non trivial updates to ReactionLines.html and the AnalysisForm (which I wrote and copied to make the MCwrapper ReactionLines.  So if anyone has a graduate student to throw at it then sure :)

typo fixed
