### ISSUE TITLE
MCW dashboard jobs table

### ISSUE THREAD

**Issue by nsjarvis** [JeffersonLab/gluex_MCwrapper#49]
I could not guess that I was supposed to access the job menu by right-clicking on the table.

I did try left-clicking, this highlighted the clicked-on job but didn't seem to do anything else.  Would it be possible to make the left-click do both things - highlight the job and open the menu popup?  If not, then *please* write something above the table to let the innocent new or forgetful users know that right-clicking/control-clicking-for-mac-users on the job of interest will access the job actions menu. 

The job actions menu was a bit worrying as it didn't look like it was working properly, the items weren't changing in any way and my cursor changed to a hard-to-see insertion mark (using chrome on mac).   If it's not possible to make the insertion mark highlight the action beneath it, could you please try spacing the action items out more, so that it's really clear as to which one the mark is over.

**Comment by T-Britton** [comment]
added a simple help alert.

I was forced to reduce the poll time on the Projects table.  This causes a sluggishness in response for certain actions. I am honestly not sure why it converts to the cursor; well I think I know why...but not the solution.  I wish it would make them bold when moused over....and I am sure it is possible but is not trivial (or not trivial to me).  Making the rows highlight took enough work lol.  So maybe one day I'll get around to it.  Or if you know of a frontend web developer well versed in raw html/js/css.....
