### ISSUE TITLE
Note of appreciation

### ISSUE THREAD

**Issue by nsjarvis** [JeffersonLab/gluex_MCwrapper#50]
MC Wrapper is super-useful despite a sometimes frustrating newbie user experience.  The help pages on how to pick which version number, etc, are really nice.  It's really good to have this facility take care of all the version varieties and random backgrounds for me.

**Comment by T-Britton** [comment]
the problem is that the whole MC process is inherently complex and intricate.  I try to hide as many knobs as possible but it still comes out better hehe.  Beats Sean asking everyone "how did you produce your MC" and everyone shrugging ;)
