### ISSUE TITLE
"get MC.config file" option

### ISSUE THREAD

**Issue by markdalton** [JeffersonLab/gluex_MCwrapper#52]
A bug has been introduced in the the get MC.config file option.  It used to be possible to get a window with some information which looked suchly:

> PROJECT=GlueX
> WORKFLOW_NAME=SDME_omega_rad_t1.8_flat_201801_20201019084701am
> NCORES=1
> GEN_MIN_ENERGY=8.199
> GEN_MAX_ENERGY=8.800
> GENERATOR=gen_amp
> GENERATOR_CONFIG=/osgpool/halld/tbritton/REQUESTEDMC_CONFIGS/1372_1372_gen_omega_rad_t1.8_flat.cfg
> COHERENT_PEAK=rcdb
> GEANT_VERSION=4
> NOSECONDARIES=0
> BKG=Random:recon-2018_01-ver02
> DATA_OUTPUT_BASE_DIR=/osgpool/halld/tbritton/REQUESTEDMC_OUTPUT/dalton/SDME_omega_rad_t1.8_flat_201801_20201019084701am
> RCDB_QUERY=@is_2018production and @status_approved
> CUSTOM_PLUGINS=file:/osgpool/halld/tbritton/REQUESTEDMC_CONFIGS/1372_jana.config
> ENVIRONMENT_FILE=/group/halld/www/halldweb/html/halld_versions/recon-2018_01-ver02_12.xml
> ANA_ENVIRONMENT_FILE=/group/halld/www/halldweb/html/halld_versions/analysis-2018_01-ver02.xml
> 

Now it looks as follows and contains no end of line characters.
![Screen Shot 2020-11-29 at 4 19 59 PM](https://user-images.githubusercontent.com/13302551/100553874-be8a9580-325e-11eb-9cdb-97076f0cb6f3.png)

PS This is on firefox on the gluon machines.  On Safari it's even worse.

**Comment by T-Britton** [comment]
I will try to get this back to working.  If I recall correctly the exact formatting is browser AND browser version dependent.  I will try to get it working on one of them (odds are this will solve several of them)

**Comment by markdalton** [comment]
If necessary this information does not have to be provided in a window. It can be downloaded in a file.

Please also put all the same information in the simulation confirmation email.  This would actually be much more convenient.

**Comment by T-Britton** [comment]
I may have found the better solution....alert over prompt.  This should globally be better, let me know.

I'll see to adding it to the confirmation email as well

**Comment by T-Britton** [comment]
should now be in the email as well

**Comment by markdalton** [comment]
Thanks.
