### ISSUE TITLE
Alternating edits hide the "analysis version Set" menu

### ISSUE THREAD

**Issue by markdalton** [JeffersonLab/gluex_MCwrapper#53]
There appears to be a bug in the web form when configuring the analysis reaction. Consider the case where an analysis reaction has already been input. Then, if editing the existing reactions using the "Add Reactions" button after saving the edited reactions, the "analysis version Set" menu does not appear. If one repeats the process of  "Add Reactions", edit, save then the "analysis version Set" menu is restored.  It repeats like this with alternating edits hiding the "analysis version Set" menu.

![Screen Shot 2020-11-30 at 12 25 28 PM](https://user-images.githubusercontent.com/13302551/100643872-9c4d5200-3308-11eb-92ba-269d637dbad9.png)

**Comment by T-Britton** [comment]
this is an odd one.  The show hide should be tied to when that text block changes and should reappear if it is empty.....or maybe When that block is visible so too should be the version set.  I'll get to it soon

**Comment by T-Britton** [comment]
just an update: it appears to be a race condition; the site hasn't yep imported the new set of reaction lines and needs to make a decision on whether or not to display the option (if it gets a blank box it should vanish)....it may take me a little longer but I think I might have a better way.  Thanks for the issue.

**Comment by T-Britton** [comment]
Fixed.
