### ISSUE TITLE
Web interface - please make the menu more obviously a menu - people aren't recognising the bars

### ISSUE THREAD

**Issue by nsjarvis** [JeffersonLab/gluex_MCwrapper#55]
Hi Thomas, 

today I explained to 2 people that the parallel bars in the top left corner of the MCW webpage are clickable and open up a menu.  They had not realised.  They had both looked all over the page for the documentation link and just weren't seeing it.   I remember I had the same problem when I was using the page for the first time.  I recognise the icon as the symbol for a collapsed menu on a cellphone, but I guess if people aren't using a cellphone it's out of context?   It's a really useful menu, though!

Please could you change the bar icon to make it more obvious?  The circled blue question marks stand out well - maybe a bigger one of those?   

Thank you.

**Comment by s6pepaul** [comment]
better late than never... done.
