### ISSUE TITLE
Sample runs within range by luminosity from CCDB

### ISSUE THREAD

**Issue by jrstevenjlab** [JeffersonLab/gluex_MCwrapper#56]
Currently when a range of runs is provided, the number of triggers is used to determine the number of events to generate for each run within the range.  This has several potential issues with sensitivity to details of the experimental setup such as TPOL converter thickness, trigger stability, etc.  (Thanks to @markdalton for pointing this out.)

The request is to use the same CCDB queries used in https://github.com/JeffersonLab/hd_utilities/blob/master/psflux/plot_flux_ccdb.py to compute the photon flux in the requested energy range for each run and use that to determine the number of events for each run.

I'm assigning this issue to myself to add this to gluex_MC.py

**Comment by jrstevenjlab** [comment]
The branch https://github.com/JeffersonLab/gluex_MCwrapper/tree/lumi_ccdb has a first stab at this flux weighting which seems to work.  The queries to CCDB and flux calculation take ~30 seconds for the full Spring 2018 dataset, which is a small upfront wait time before the jobs can be submitted for each run.  If that's a price we're willing to pay, then I think this branch would address the concerns @markdalton raised.

**Comment by markdalton** [comment]
Personally, I think that for something that always gives the right breakdown of events per run, it's worth it.

**Comment by T-Britton** [comment]
I agree.  We'll get this pulled in to the DEV branch for final testing before merging it to master and releasing :)

**Comment by T-Britton** [comment]
it is in and working
