### ISSUE TITLE
AUGER-FAILED on ifarm with MCWrapper/gen_amp

### ISSUE THREAD

**Issue by igjaegle** [JeffersonLab/gluex_MCwrapper#64]
Since 3 to 4 weeks, whenever I used MCWrapper with gen_amp in batch mode 2 with my local halld_recon/simu and hdgeant4, all my jobs are failing with an AUGER-FAILED error type. There are no log outputs, the only error recorded is the one by swif
e.g.
{
    "problem_type_name": "AUGER-FAILED",
    "workflow_name": "xxx",
    "job_name": "xxx-299",
    "auger_id": 30700564,
    "auger_state": "FAILED",
    "job_run_id": 1987151487,
    "job_id": 37620440,
    "job_options_id": 55100,
    "workflow_id": 141632
  }
I retried the jobs multiple times but always get an AUGER-FAILED error type. But, the simulation is working smoothly if run interactively.  Also, if I am using another event generator for example genEtaRegge there are no problems when used in batch mode 2.

**Comment by T-Britton** [comment]
There is zero evidence this is an MCwrapper issue. With no log files and a working genEtaRegge and a working interactive running (they use exactly the same swif submit mechanism….which uses auger) I do not see how this could be MCwrapper’s fault.

Further, this apparently was working a few weeks ago. If you haven’t changed your MCwrapper then it most certainly is not an MCwrapper problem.

**Comment by aaust** [comment]
It looks like you are trying to write the log files to a folder that does not exist:
`FAILED (Job failed due to invalid stdout/stderr)`

**Comment by igjaegle** [comment]
Thank you, Alex. Indeed, this was a very stupid mistake.

tks ig.
