### ISSUE TITLE
Feature request: root file merging / job cleanup on farm

### ISSUE THREAD

**Issue by jonzarling** [JeffersonLab/gluex_MCwrapper#78]
When analysis launches are performed, we perform a second pass to merge root trees. This reduces the number of files by a pretty large factor. Could we do something similar for completed MCWrapper jobs submitted from the web form? Some of my larger samples wind up approaching ~ 100k files, which is difficult to stat and probably not very nice to the lustre system. 

Also, I recall some .tar files that would populate some of the top level directories, but maybe those have been removed now.

**Comment by T-Britton** [comment]
this would be interesting.... people mind waiting to get their data until after the project finishes? I need to think through the logic (the complication that prevented this in the past).  I wonder if I can untar and retar as files complete.....

**Comment by s6pepaul** [comment]
this should now be implemented for jobs submitted via the submission form. There is a bit of a backlog right now. But it should start to clear soon. Closed.
