### ISSUE TITLE
Issue with run number format

### ISSUE THREAD

**Issue by markito3** [JeffersonLab/gluex_MCwrapper#8]
There is an issue opened on the hd_utilities repository on run numbers. It is [Issue 62](https://github.com/JeffersonLab/hd_utilities/issues/62).

**Comment by T-Britton** [comment]
This only effects hdgeant4.  MCwrapper now trims leading zeroes from run numbers.  This works for ranges as well.  This change is in the DEV branch and will be included in the next release.

**Comment by T-Britton** [comment]
fixed in dev branch
