### ISSUE TITLE
Assumption about CUSTOM_PLUGINS file format

### ISSUE THREAD

**Issue by jrstevenjlab** [JeffersonLab/gluex_MCwrapper#81]
For reproducing analysis launches by running ReactionFilter with a different analysis library, this line https://github.com/JeffersonLab/gluex_MCwrapper/blob/master/MakeMC.sh#L1698 assumes that the first line of the `CUSTOM_PLUGINS` JANA configuration file contains the list of plugins used in the previous reconstruction step.  With this assumption you can remove the list of plugins and safely replace it with `PLUGINS ReactionFilter` so that only that one plugin is run in the second step where the ROOT tree is made for analysis.

However, for those not running on the OSG the JANA configuration file can have any order and the first line may not be the list of plugins to be run.  This can result in the wrong line being deleted and the wrong list of plugins being run in the analysis step.

I'd suggest making this more robust by specifically deleting the line which contains `PLUGINS` from `jana_config.cfg` and replacing it with `PLUGINS ReactionFilter`

**Comment by s6pepaul** [comment]
addressed by #95
