### ISSUE TITLE
Feature Request: Add +NoTag option to web form

### ISSUE THREAD

**Issue by maltealbrecht** [JeffersonLab/gluex_MCwrapper#85]
When generating large MC samples for partial wave analyses, in general we do not need to generate tagger accidentals (however keep the detector random hits!). Peter let me know that I can use something like `BKG=Random:recon-2018_01-ver02.2+NoTag` to achieve that in my config file, when manually submitting jobs using `gluex_MC.py`. 

Could we add a checkbox or something to the webform, so this option is usable to generate larger samples?

**Comment by s6pepaul** [comment]
Done
