### ISSUE TITLE
Add warning to genr8 example: mcthrown_tree plugin may not work with generator

### ISSUE THREAD

**Issue by jonzarling** [JeffersonLab/gluex_MCwrapper#86]
The default behavior of the mcthrown_tree plugin is to store the 4-vectors **only if** there is a reconstructed hit in the tagger. This is needed for properly applying _tagged_ flux normalizations. There's a little snag when using genr8 though- it looks like if you force a monoenergetic beam photon (the old way, before beam config files were supported with genr8) you'll guarantee a tagger hit for each event. Therefore, you'll be off by a factor of 1/tagger_efficiency anytime you try to normalize.

Hopefully no one's actually doing this, but just in case I think it would help to add a warning in the example config.

**Comment by s6pepaul** [comment]
addressed by #95
