### ISSUE TITLE
Web Interface Simplification

### ISSUE THREAD

**Issue by imoewi01** [JeffersonLab/gluex_MCwrapper#88]
I think the web submission form can be simplified a bit. The majority of users will use the most recent halld_sim and recon versions. I would suggest keeping the current submit form for "expert" submission requests, and have a simplified version where the user specifies one (or more) run period(s). The most recent software versions can be used, and the run range and RCDB command should default to all approved production runs in a run period. 

It would also be great if there was an option for all of phase 1. This would require the user to specify the analysis version for each run period separately, but it would reduce the number of times we need to fill out the form.

**Comment by T-Britton** [comment]
this has been a suggestion.  A drop down to select a run range.  The analysis launch wrinkle is the real "problem".  Peter was going to take a crack at it "soon" to enhance things a bit....but if you cut analysis you are potentially adding the work back in (and with a greater chance of mistakes).  There is a way to copy projects which should drastically cut down on the number of times one must refill;  I am all for adding tags that auto set the run range :)

**Comment by s6pepaul** [comment]
Indeed, a makeover of the submission page is on my list. I want to streamline it similarly to what you described. I hope to have a stab at this soon.

**Comment by s6pepaul** [comment]
Most these suggestions are now addressed with the new webpage. For various reasons I am quite hesitant to a "all of phase-1" button. The user can copy projects from the dashboard and easily resubmit for a different beam time. I think for now that is best.
