### ISSUE TITLE
Adding support for bggen_upd

### ISSUE THREAD

**Issue by sdobbs** [JeffersonLab/gluex_MCwrapper#90]
There's an updated version of bggen / bggen_jpsi in halld_sim called bggen_upd.  You can find it in - halld_sim/src/programs/Simulation/bggen_upd

It would be nice to have support for this generator as well - there's pretty good documentation included with the generator, but Lubomir, Eugene, or I could answer questions.

**Comment by s6pepaul** [comment]
#91 should incorporate the last changes that were needed to get it to run with MCwrapper. Test jobs on the OSG are running and seem fine. Let me know if there are any issues that pop up. For now I close this.
