### ISSUE TITLE
repeating generated events from input HDDM file?

### ISSUE THREAD

**Issue by jrstevenjlab** [JeffersonLab/gluex_MCwrapper#99]
I was looking into the option to pass an HDDM file to MCWrapper rather than using one of the available generators.  In the MakeMC scripts there is an implementation to skip events in the provided HDDM file by N = FILE_NUMBER * PER_FILE

https://github.com/JeffersonLab/gluex_MCwrapper/blob/master/MakeMC.sh#L1418

This seems like it would produce a unique subset of events if one generates events for just a single run.  But if the same input HDDM file is used to generate events for many runs, won't this result in the first file for each run starting at event = 0 in the input HDDM file, which will duplicate the same generated events for each run number?  If so, is there an index for the run number that could be added to this skip to avoid repeating generated events when this input HDDM file is used?

**Comment by T-Britton** [comment]
repeat issue: https://github.com/JeffersonLab/gluex_MCwrapper/issues/16

it is fairly non trivial. May be worth another crack at given we are through the python 2 v 3 pains
